pub const EDGE_I444_TOP_HAS_RIGHT: u8 = 1 << 0;
pub const EDGE_I422_TOP_HAS_RIGHT: u8 = 1 << 1;
pub const EDGE_I420_TOP_HAS_RIGHT: u8 = 1 << 2;
pub const EDGE_I444_LEFT_HAS_BOTTOM: u8 = 1 << 3;
pub const EDGE_I422_LEFT_HAS_BOTTOM: u8 = 1 << 4;
pub const EDGE_I420_LEFT_HAS_BOTTOM: u8 = 1 << 5;

pub const EDGE_ALL_TOP_HAS_RIGHT: u8 =
    EDGE_I444_TOP_HAS_RIGHT | EDGE_I422_TOP_HAS_RIGHT | EDGE_I420_TOP_HAS_RIGHT;
pub const EDGE_ALL_LEFT_HAS_BOTTOM: u8 =
    EDGE_I444_LEFT_HAS_BOTTOM | EDGE_I422_LEFT_HAS_BOTTOM | EDGE_I420_LEFT_HAS_BOTTOM;
pub const EDGE_ALL_TR_AND_BL: u8 = EDGE_ALL_TOP_HAS_RIGHT | EDGE_ALL_LEFT_HAS_BOTTOM;
