//! Build script for rav2d.
//!
//! On aarch64 it assembles dav2d's hand-written NEON motion-compensation
//! kernels (`dav2d/src/arm/64/mc.S` + `mc_dotprod.S`) and the two read-only data
//! tables they reference (`dav2d_mc_subpel_filters`, `dav2d_mc_warp_filter`),
//! linking them into the rav2d staticlib so the decoder can dispatch the MC DSP
//! family to NEON (see `src/mc_neon.rs`). The dav2d submodule is referenced
//! read-only; nothing under `dav2d/src` or `dav2d/include` is modified.
//!
//! On other architectures this is a no-op and the decoder uses the scalar Rust
//! kernels in `src/mc.rs`.

use std::env;
use std::path::{Path, PathBuf};

fn main() {
    // Declare the cfg we may set so rustc's unexpected-cfg lint stays quiet.
    println!("cargo:rustc-check-cfg=cfg(rav2d_neon_mc)");
    if env::var("CARGO_CFG_TARGET_ARCH").as_deref() == Ok("aarch64") {
        build_neon_mc();
    }
}

fn build_neon_mc() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let dav2d = manifest.join("../../dav2d");
    let dav2d = dav2d.canonicalize().unwrap_or(dav2d).to_path_buf();
    let src = dav2d.join("src");
    let include = dav2d.join("include");
    let build = dav2d.join("build");
    let build_src = build.join("src");

    let mc_s = src.join("arm/64/mc.S");
    let mc_dotprod_s = src.join("arm/64/mc_dotprod.S");
    let config_h = build.join("config.h");

    // If the dav2d build artifacts (config.h, asm-offsets.h) aren't present we
    // can't assemble the kernels; fall back to scalar by skipping cleanly.
    if !mc_s.exists() || !config_h.exists() {
        println!(
            "cargo:warning=dav2d asm sources not found ({}); rav2d MC will use scalar Rust",
            mc_s.display()
        );
        return;
    }

    println!("cargo:rerun-if-changed={}", mc_s.display());
    println!("cargo:rerun-if-changed={}", mc_dotprod_s.display());
    println!("cargo:rerun-if-changed={}", src.join("arm/asm.S").display());
    println!(
        "cargo:rerun-if-changed={}",
        src.join("arm/64/util.S").display()
    );
    println!("cargo:rerun-if-changed={}", config_h.display());
    println!("cargo:rerun-if-changed=build.rs");

    // Generate the data-table C file from dav2d/src/tables.c (verbatim bytes) so
    // the asm's `dav2d_mc_subpel_filters` / `dav2d_mc_warp_filter` references
    // resolve. Regenerated each build; dav2d source is never modified.
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let tables_c = out_dir.join("mc_tables.c");
    generate_mc_tables(&src.join("tables.c"), &tables_c);
    println!("cargo:rerun-if-changed={}", src.join("tables.c").display());

    // Shared include dirs matching dav2d's own build (see build.ninja).
    let includes: [&Path; 6] = [
        &src.join("arm/64"), // util.S
        &src,                // src/arm/asm.S, src/mc.h
        &dav2d,              // "src/..." relative includes
        &include,            // common/attributes.h, dav2d/headers.h
        &build,              // config.h (#include "config.h")
        &build_src,          // generated headers
    ];

    let mut cc = cc::Build::new();
    cc.file(&mc_s).file(&mc_dotprod_s).file(&tables_c);
    for inc in includes {
        cc.include(inc);
    }
    // Match dav2d's release flags for the asm/data. NDEBUG keeps assert() out of
    // the asm macros; PIC is already defined in config.h so we don't pass -DPIC.
    cc.define("NDEBUG", None);
    cc.flag_if_supported("-std=c99");
    // The .S use the .arch/.arch_extension directives gated by config.h; clang
    // handles them. Silence the benign config.h-controlled warnings.
    cc.warnings(false);
    cc.compile("rav2d_mc_neon");

    // Tell the linker NEON MC is available so src/mc_neon.rs enables dispatch.
    println!("cargo:rustc-cfg=rav2d_neon_mc");
}

/// Copy the two MC data tables out of `dav2d/src/tables.c` verbatim into a small
/// standalone C translation unit. Only `dav2d_mc_subpel_filters` and
/// `dav2d_mc_warp_filter` are needed by the asm.
fn generate_mc_tables(tables_c: &Path, out: &Path) {
    let src = std::fs::read_to_string(tables_c).expect("read dav2d tables.c");
    let lines: Vec<&str> = src.lines().collect();

    let grab = |marker: &str| -> String {
        let start = lines
            .iter()
            .position(|l| l.contains(marker))
            .unwrap_or_else(|| panic!("table {marker} not found in tables.c"));
        let mut out = Vec::new();
        for l in &lines[start..] {
            out.push(*l);
            if l.trim() == "};" {
                break;
            }
        }
        out.join("\n")
    };

    let subpel = grab("dav2d_mc_subpel_filters[6][15][8]");
    let warp = grab("dav2d_mc_warp_filter[7*64+1][8]");

    let content = format!(
        "/* Generated by rav2d build.rs from dav2d/src/tables.c (verbatim). Provides\n\
         * the read-only data tables dav2d's NEON MC kernels reference. Do not edit. */\n\
         #include \"config.h\"\n\
         #include <stdint.h>\n\
         #include \"common/attributes.h\"\n\
         #include \"dav2d/headers.h\"\n\n\
         {subpel}\n\n\
         {warp}\n"
    );
    std::fs::write(out, content).expect("write generated mc_tables.c");
}
